# Generated by Django 4.2.5 on 2023-09-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                ("aaadhar", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=100)),
                ("emer1_name", models.CharField(max_length=100)),
                ("emer1_number", models.CharField(max_length=10)),
                ("emer1_address", models.CharField(blank=True, max_length=100)),
                ("emer2_name", models.CharField(max_length=100)),
                ("emer2_number", models.CharField(max_length=10)),
                ("emer2_address", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
