# Generated by Django 4.2.5 on 2023-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=3214, max_length=100),
            preserve_default=False,
        ),
    ]
