# Generated by Django 4.2.5 on 2023-09-22 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                ("speciality_id", models.AutoField(primary_key=True, serialize=False)),
                ("speciality", models.CharField(max_length=100)),
                (
                    "agency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agency.agency"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                (
                    "agency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agency.agency"
                    ),
                ),
            ],
        ),
    ]
