# Generated by Django 4.2.5 on 2023-09-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0002_speciality_inventory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="speciality",
            old_name="speciality",
            new_name="name",
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "agency_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agency.agency"
                    ),
                ),
            ],
        ),
    ]
