# Generated by Django 4.2.5 on 2023-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='location',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='name',
            field=models.TextField(),
        ),
    ]
