# Generated by Django 4.2.5 on 2023-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdash", "0002_remove_broadcast_location_broadcast_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="type",
            field=models.TextField(default=23),
            preserve_default=False,
        ),
    ]
