# Generated by Django 4.2.5 on 2023-10-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userdash", "0003_broadcast_is_active_broadcast_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcast",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
