# Generated by Django 4.2.5 on 2023-10-27 21:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0002_user_password"),
        ("userdash", "0004_alter_broadcast_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("description", models.TextField()),
                ("locality", models.TextField()),
                ("tags", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_answered", models.BooleanField(default=False)),
                ("answer", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentification.user",
                    ),
                ),
            ],
        ),
    ]
